### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by kelaun** [layday/instawow#48] opened 2020-09-10 20:08 UTC
In reference to #33 

Would you perhaps be interested if someone else would maintain said package?
I might attempt to create this AUR package next week (it would be my first AUR package) if you agree with this.

**Comment by layday** [comment] 2020-09-10 20:16
I'm completely fine with that if you're willing to take on the burden of keeping it reasonably up to date ;)

**Comment by kelaun** [comment] 2020-09-10 20:29
Thanks.
I'll check that next week and inform here once it is there so you can update the README.

**Comment by kelaun** [comment] 2020-09-10 22:02
Actually, it is already there as of today. I had some free time.
[https://aur.archlinux.org/packages/instawow/](https://aur.archlinux.org/packages/instawow/)

**Comment by layday** [comment] 2020-09-10 22:07
Thanks for doing this.  Will it install all of instawow's dependencies even when they aren't specified in PKGBUILD?

**Comment by kelaun** [comment] 2020-09-10 22:32
You mean the ones from the setup.py? 
If so, I checked and have none of these and it still works, could you perhaps clarify why they are needed?

**Comment by layday** [comment] 2020-09-10 22:48
I just don't see how it'd work without the depedencies - are you testing with the version from AUR? ;)  You would at the very least need to specify `setuptools_scm` and `toml` as build-time dependencies, otherwise the migrations and WA templates will not be packaged, `_version.py` will not be generated and instawow will be installed with a version number of `0.0.0`.  A `check` step would definitely help assuade my, erm, doubtsIncidentally I'd also prefer it if you pulled the sdist from PyPI - this should be `https://files.pythonhosted.org/packages/source/${_name::1}/$_name/$_name-$pkgver.tar.gz` according to the [Arch documentation](https://wiki.archlinux.org/index.php/Python_package_guidelines#Source)` - instead of from GitHub.  

Again, thanks for tackling this and I'm sorry if I'm a little picky - I just wanna make sure it works suitably well before adding it to the readme.

**Comment by kelaun** [comment] 2020-09-10 22:52
I am indeed testing with the AUR version. Actually I did check and indeed the version says `instawow, version dev` so this is not correct.
I will also change the pull to be from PyPI.

**Comment by layday** [comment] 2020-09-10 22:56
(Sorry, I closed the issue by accident while attempting to comment!)

I just don't see how it'd work without the depedencies - are you testing with the version from AUR? ;)  You would at the very least need to specify `setuptools_scm` and `toml` as build-time dependencies, otherwise the migrations and WA templates will not be packaged, `_version.py` will not be generated and instawow will be installed with a version number of `0.0.0`.  A `check` step would definitely help assuade my, *erm*, doubts - although `aresponses` isn't available on the AUR which poses a bit of an issue.  I'd also prefer it if you pulled the dist from PyPI.

Again, thanks for tackling this and I'm sorry if I'm a little picky - I just wanna make sure it works suitably well before adding it to the readme.

**Comment by kelaun** [comment] 2020-09-10 23:20
Ok, I am busy with adapting, but have some questions for you.
The following packages are not available for Arch currently:
- slpp
- aiohttp-rpc
- aresponses

Could you let me know if these are needed or not? If they are needed, they will need to be packaged as well.

**Comment by layday** [comment] 2020-09-10 23:23
* aresponses is only needed for running the tests
* aiohttp-rpc is only needed for running the GUI
* slpp is needed for building the WeakAuras Companion add-on

**Comment by kelaun** [comment] 2020-09-11 00:09
The dependencies are all fixed now. Only open point is to have a check in the PKGBUILD.
I'll look into that later as it is now 2 a.m. here :smile:

**Comment by layday** [comment] 2020-09-11 00:44
Brilliant, thank you.  To test it add the following to `checkdepends`:

```
('python-pytest>=6.0.1' 'python-pytest-asyncio' 'python-aresponses')
```

... then add a `check` function to your `PKGBUILD` calling pytest:


```sh
check() {
    cd "$pkgname-$pkgver"
    pytest
}
```

I noticed that you've hardcoded the sdist URL but this should work:

```
source=("$pkgname-v$pkgver.tar.gz:https://files.pythonhosted.org/packages/source/${pkgname::1}/$pkgname/$pkgname-$pkgver.tar.gz")
```

... and would expand to `https://files.pythonhosted.org/packages/source/i/instawow/instawow-1.14.1.tar.gz`.

In your `makedepends` you should only have `setuptools`, `setuptools_scm` and `toml`.  Everything else should go in (runtime) `depends`.

Finally (!), if you could please update the license to 'GPL3' - 'GPL' is for GPLv2.

**Comment by kelaun** [comment] 2020-09-11 08:06
So, I think we're there now :smile:

**Comment by layday** [comment] 2020-09-11 09:43
Almost ;) 'python-jinja-time' should be 'python-jinja'.  Sorry, I missed that earlier.

**Comment by kelaun** [comment] 2020-09-11 10:32
It is changed.

**Comment by layday** [comment] 2020-09-11 11:07
Okay, I set up Arch in a VM and tried to install instawow from the AUR.  It tells me that the python-loguru, python-questionary, python-slpp-git and python-aresponses 'targets' can't be found.  I assume this is because these packages are on the AUR and not in one of the main repos.  Will users have to install them manually?

**Comment by layday** [comment] 2020-09-11 11:18
Right, okay, so `yay` is a tool from the AUR which handles AUR dependencies (it's AUR packages all the way down).  I tried installing it with `yay` and the tests don't run - I believe we might've to extend the `PYTHONPATH`.  Is there a way to run `yay` on a local package?

**Comment by layday** [comment] 2020-09-11 11:27
Okay, I changed `pytest` to `python -m pytest` which puts the cwd on the `PYTHONPATH` automagically.  The tests won't run without `aiohttp-rpc` but I think we can safely ignore `tests/test_json_rpc_api.py` - it's unlikely anyone will run the server on Arch, ever.

**Comment by kelaun** [comment] 2020-09-11 11:29
So I checked on a VM as well and indeed `yay -S instawow` does not work.
The error I get is the following:
`ImportError while loading conftest '/home/kelaun/.cache/yay/instawow/src/instawow-1.4.1/tests/conftest.py'.
test/conftest.py:7: in <module>
  from instawow.config import Config
E ModuleNotFoundError: No module named 'instawow'`

**Comment by layday** [comment] 2020-09-11 11:31
Try this:

```diff
diff --git a/PKGBUILD b/PKGBUILD
index 5fd229c..c4d3024 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -20,7 +20,7 @@ build() {

 check() {
        cd "$pkgname-$pkgver"
-       pytest
+       python -m pytest --ignore tests/test_json_rpc_api.py
 }

 package() {
```

**Comment by kelaun** [comment] 2020-09-11 11:38
Thanks, it seems to work. However the tests/test_cli_output.py is really slow (VM with 4GB RAM and 2 cores)

**Comment by layday** [comment] 2020-09-11 11:38
On second thought, we should be testing the build - not the source package - so:

```diff
diff --git a/PKGBUILD b/PKGBUILD
index 5fd229c..a93171a 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -20,7 +20,7 @@ build() {

 check() {
        cd "$pkgname-$pkgver"
-       pytest
+       PYTHONPATH="$PWD/build/lib" pytest --ignore tests/test_json_rpc_api.py
 }

 package() {
```

However, the tests hang for me...

**Comment by kelaun** [comment] 2020-09-11 11:56
It gets stuck on the following:
`tests/test_cli_output.py::test_valid_curse_pkg_lifecycle[retail-install curse:molinari-<lambda>]`

**Comment by layday** [comment] 2020-09-11 11:59
Does it still get stuck after modifying the `PYTHONPATH`?

**Comment by kelaun** [comment] 2020-09-11 12:00
Yes, still the same.

**Comment by kelaun** [comment] 2020-09-11 12:12
It is really something wrong in the testing itself. When disabling the check part, I am able to install the package and it is fully working when I test it out. Even the version is set properly.

**Comment by layday** [comment] 2020-09-11 12:20
Well, the tests are working for me now but I've no idea why or how 🤷‍♂️

We could just comment them out and reinstate them when I manage to figure out whatever's going on.

**Comment by kelaun** [comment] 2020-09-11 12:21
I ignore tests/test_cli_output.py and it works as well.
Seems something is wrong in there.

**Comment by kelaun** [comment] 2020-09-11 12:25
Ok weird. It works when I reinstall all the dependencies...

**Comment by layday** [comment] 2020-09-11 12:25
It's not easy for me to debug if I can't reproduce it anymore!

**Comment by kelaun** [comment] 2020-09-11 12:27
In the AUR I ignore the cli test. But I will try with clean install now.

**Comment by kelaun** [comment] 2020-09-11 12:44
It seems to work fine now for me. I don't know what caused us both to have an issue though.

**Comment by kelaun** [comment] 2020-09-11 13:28
So I've been testing some more and I can't seem to make it work on a new install anymore. 
The version in AUR that omits the test_cli_output.py works however on all installs I've been doing.
Even with verbose on pytest turned on, I don't see any error message however.

**Comment by layday** [comment] 2020-09-11 13:39
Well, if we keep the CLI tests in, whoever comes across this issue will either help us debug it or it will put them off instawow forever<sup> and ever<sup> and ever</sup></sup>.  In the spirit of free software, I would argue that the former is preferable.

**Comment by kelaun** [comment] 2020-09-11 13:42
So you would prefer to have them in and the installer being stuck? 
Or am I understanding you wrong and an `--ignore tests/test_cli_output.py` is fine for you in the check function?

**Comment by layday** [comment] 2020-09-11 13:53
Okay, keep it ignored for now then.  If there's nothing left to do, I'll merge the PR and we can close this.

**Comment by kelaun** [comment] 2020-09-11 14:07
Another option is to install the wheel package with pip instead. But I don't know if pip runs any tests though when installing that one.
If it doesn't I would keep on using the tar file instead.

**Comment by layday** [comment] 2020-09-11 14:12
pip does not run tests and the tests are not packaged with the wheel.  Running pip would also be rather unusual - pip is not *ahem* highly thought of among distro packagers.

**Comment by kelaun** [comment] 2020-09-11 14:13
Indeed, wanted to edit my post as I noticed it does not test.
You were to fast :smile: 
I would keep it as is. It is working, but skips the cli tests currently.

**Comment by layday** [comment] 2020-09-11 14:21
Alright, the tests are due an overhaul anyway. We can try re-enabling the CLI tests when I've given them a proper look. Thanks for working on getting instawow in the AUR 🚀

**Closed by layday** 2020-09-11 14:21 UTC
